version: '2'

services:
  app:
    image: demo-jconfcentroamerica-2020:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demodb?useUnicode=true&characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=demo
      - SPRING_DATASOURCE_PASSWORD=demo
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8.0.22
    environment:
      - MYSQL_DATABASE=demodb
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      - type: bind
        source: ./src/test/resources/sql/schema.sql
        target: /docker-entrypoint-initdb.d/script1.sql
        read_only: true
      - type: bind
        source: ./src/test/resources/sql/data.sql
        target: /docker-entrypoint-initdb.d/script2.sql
        read_only: true
  redis:
    image: redis:5.0.6
